import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import NavBar from "../components/NavBar";
import {BiSearch} from "react-icons/bi/index"
import Image from "next/image";


const Home: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#411a1a] to-[#0a0a0a] pb-5">
        <NavBar />
        <div className="mt-3">
          <div className="search-sec flex p-2 items-center gap-5 relative">
            <input type="text" className="w-[98%] rounded-sm p-2" placeholder="Search for product" />
            <BiSearch className="absolute right-6 text-xl" />
          </div>
        </div>

        <div className="product-container w-[96%] mx-auto rounded flex flex-col bg-[#413434] justify-center mt-5">
          <div className="card shadow-sm shadow-slate-900 bg-[#705b5b] w-full rounded flex justify-center">
            <Image src={"http://cdn.shopify.com/s/files/1/0015/2602/products/YellowSockMain_grande.png?v=1639085468"} alt={"prod-img"} width={250} height={200} />
          </div>
          <div className=" p-2">
            <div className="flex justify-between">
              <p className="font-semibold text-xl text-zinc-300">Name of Socks</p>
              <div className="flex text-slate-300">
                <p className="text-xl">-</p>
                <div className="bg-slate-600 flex justify-center items-center mx-2 px-2 rounded ">
                    8
                </div>
                <p className="text-xl">+</p>
              </div>
            </div>
            <p className="text-sm  text-zinc-400">More descriptions of socks</p>
            <p className="text-sm text-zinc-400">Current Stock: 20</p>

          </div>
        </div>
        <div className="product-container w-[96%] mx-auto rounded flex flex-col bg-[#413434] justify-center mt-5">
          <div className="card shadow-sm shadow-slate-900 bg-[#705b5b] w-full rounded flex justify-center">
            <Image src={"http://cdn.shopify.com/s/files/1/0015/2602/products/YellowSockMain_grande.png?v=1639085468"} alt={"prod-img"} width={250} height={200} />
          </div>
          <div className=" p-2">
            <p className="font-semibold text-xl text-zinc-300">Name of Socks</p>
            <p className="text-sm text-zinc-400">More descriptions of socks</p>
            <p className="text-sm text-zinc-400">Current Stock: 20</p>

          </div>
        </div>
        
      </main>
    </>
  );
};

export default Home;

