import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import NavBar from "../components/NavBar";
import {BiSearch} from "react-icons/bi/index"
import Image from "next/image";


const Home: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#411a1a] to-[#0a0a0a]">
        <NavBar />
        <div className="mt-3">
          <div className="search-sec flex p-2 items-center gap-5 relative">
            <input type="text" className="w-[98%] rounded-sm p-2" placeholder="Search for product" />
            <BiSearch className="absolute right-6 text-xl" />
          </div>
        </div>

        <div className="product-container flex justify-center mt-5">
          <div className="card bg-[#705b5b] shadow-md shadow-slate-900 w-[92%] rounded flex justify-center">
            <Image src={"http://cdn.shopify.com/s/files/1/0015/2602/products/YellowSockMain_grande.png?v=1639085468"} alt={"prod-img"} width={250} height={200} />
          </div>
        </div>
        
      </main>
    </>
  );
};

export default Home;

